[[dav-properties]]
== New DAV and CALDAV properties

=== DAV:subscription

Name:: subscription
Namespace:: DAV
Purpose:: To indicate that the resource is a subscription to an external resource which is
managed by the server.
Conformance:: When this is specified the request MUST also contain at least a
DAV:subscription-href element as defined in this specification.
Description:: The DAV:specification resource type element is used to indicate a collection
that is a subscription. A subscription MUST report the DAV:subscription XML element in the
value of the DAV: resourcetype property.
Definition::
+
[source%unnumbered]
----
<!ELEMENT subscription empty>
----

=== DAV:subscription-href

Name:: subscription-href
Namespace:: DAV
Purpose:: Provides the url for the external subscription.
Conformance:: This property MUST be defined on any collection which has a resource-type
containing a DAV:subscription element.
Definition::
+
[source%unnumbered]
----
<!ELEMENT vpoll-max-items (#PCDATA)>
PCDATA value: a url
----
Example::
+
[source%unnumbered]
----
<D:subscription-href xmlns:D="DAV"
>https://example.com/events.ics</D:subscription-href>
----

=== DAV:subscription-deletions-suppressed

Name:: subscription-deletions-suppressed
Namespace:: DAV
Purpose:: To indicate that resources that no longer appear in the feed should be retained by
the server.
Conformance:: This property MAY be defined on any subscription.
Description:: Many feeds provide only the current active set of resources. For example, a
calendar feed may only contain events from the current date onwards - while many subscribers
would like to retain a copy of all events received over time.
+
This property indicates that the server SHOULD retain resources that disappear from the feed.
Services MAY define some mechanism to indicate that a particular resource SHOULD be removed.
For example this specification suggests setting a status of DELETED on a calendar event.
Definition::
+
[source%unnumbered]
----
<!ELEMENT subscription-deletions-suppressed empty>
----

=== DAV:subscription-disabled

Name:: subscription-disabled
Namespace:: DAV
Purpose:: To indicate that subscription has been disabled.
Conformance:: This property MUST be reported for any disabled subscription.
Description:: A server MAY choose to disable a subscription if there is an excessive number of
errors when attempting to synchronize with the target This property indicates to the client
that the subscription has been disabled.
+
There is no explicit action that can be taken to reenable a subscription. However, on
subsequent requests a client may indicate a refresh is desired which MAY have the effect of
reenabling the subscription.
Definition::
+
[source%unnumbered]
----
<!ELEMENT subscription-enabled empty>
----

=== DAV:subscription-next-refresh-interval

Name:: subscription-next-refresh-interval
Namespace:: DAV
Purpose:: To indicate the time interval till the next refresh of a subscription.
Conformance:: This property MUST be reported for any active subscription.
Description:: This provides a time period to the next refresh. It uses the period format
defined in <<RFC3339>>.
Definition::
+
[source%unnumbered]
----
<!ELEMENT subscription-next-refresh-interval (#PCDATA)>
PCDATA value: a duration value
----
Example::
+
[source%unnumbered]
----
<D:subscription-next-refresh-interval xmlns:D="DAV"
>PT30M</D:subscription-next-refresh-interval>
----

=== DAV:subscription-suggested-refresh-interval

Name:: subscription-suggested-refresh-interval
Namespace:: DAV
Purpose:: To indicate the desired time interval between refreshes of a subscription.
Conformance:: This property MUST be reported for any active subscription.
Description:: This provides a suggested time period between refresh. It uses the period format
defined in RFC 3339.
Definition::
+
[source%unnumbered]
----
<!ELEMENT subscription-suggested-refresh-interval (#PCDATA)>
PCDATA value: a duration value
----
Example::
+
[source%unnumbered]
----
<D:subscription-suggested-refresh-interval xmlns:D="DAV"
>PT30M</D:subscription-suggested-refresh-interval>
----
